language: swift
xcode_project: ThunderTable.xcodeproj # path to your xcodeproj folder
osx_image: xcode11
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderTable
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max
